// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9ah3aO3iIfXyjuFGt4iYwBb3NEEWjZw',
    appId: '1:400985329837:web:878aaba3648bdb02917624',
    messagingSenderId: '400985329837',
    projectId: 'phd-discussions',
    authDomain: 'phd-discussions.firebaseapp.com',
    storageBucket: 'phd-discussions.appspot.com',
    measurementId: 'G-MV1F0RVB08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbkUB2y3UIqVuD-FS3xl4ATBHrAulV31s',
    appId: '1:400985329837:android:e3708d5daf7d84c2917624',
    messagingSenderId: '400985329837',
    projectId: 'phd-discussions',
    storageBucket: 'phd-discussions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcK1C_KYmqObktNVOlQwUjBdQJ25mHqJU',
    appId: '1:400985329837:ios:6467a3ca7d71d55b917624',
    messagingSenderId: '400985329837',
    projectId: 'phd-discussions',
    storageBucket: 'phd-discussions.appspot.com',
    iosBundleId: 'com.example.phdDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcK1C_KYmqObktNVOlQwUjBdQJ25mHqJU',
    appId: '1:400985329837:ios:6467a3ca7d71d55b917624',
    messagingSenderId: '400985329837',
    projectId: 'phd-discussions',
    storageBucket: 'phd-discussions.appspot.com',
    iosBundleId: 'com.example.phdDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG9ah3aO3iIfXyjuFGt4iYwBb3NEEWjZw',
    appId: '1:400985329837:web:ca064b5107a49531917624',
    messagingSenderId: '400985329837',
    projectId: 'phd-discussions',
    authDomain: 'phd-discussions.firebaseapp.com',
    storageBucket: 'phd-discussions.appspot.com',
    measurementId: 'G-WM9KJV7LVN',
  );
}
